// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabJc_Qv0OUz_GT2RIb6u6AMlelRNGkVY',
    appId: '1:666602056920:web:adbe5fca43a29d98a4fbad',
    messagingSenderId: '666602056920',
    projectId: 'bloc-flutter-e07dc',
    authDomain: 'bloc-flutter-e07dc.firebaseapp.com',
    storageBucket: 'bloc-flutter-e07dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_X-D7cUnlzbFzEjK5hrGduUmrk5Lu28',
    appId: '1:666602056920:android:538c02737598b7f6a4fbad',
    messagingSenderId: '666602056920',
    projectId: 'bloc-flutter-e07dc',
    storageBucket: 'bloc-flutter-e07dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGnCGmkb7hfibBN133CqXDyWYR8n426fI',
    appId: '1:666602056920:ios:78e81a8f64f74592a4fbad',
    messagingSenderId: '666602056920',
    projectId: 'bloc-flutter-e07dc',
    storageBucket: 'bloc-flutter-e07dc.appspot.com',
    iosBundleId: 'com.example.blockFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGnCGmkb7hfibBN133CqXDyWYR8n426fI',
    appId: '1:666602056920:ios:dcd2f2f1a95d6538a4fbad',
    messagingSenderId: '666602056920',
    projectId: 'bloc-flutter-e07dc',
    storageBucket: 'bloc-flutter-e07dc.appspot.com',
    iosBundleId: 'com.example.blockFirebase.RunnerTests',
  );
}
